// =========================================
// BASE DE DONNÉES GLOBALE - DAR AL-KALIMAH
// =========================================
const wordsDatabase = [
    // ALPHABET (1-28)
    { id: 1, type: "letter", arabe: "أ", fr: "Lettre Alif", es: "Letra Alif", audio: "audio/01-alif.mp3" },
    { id: 2, type: "letter", arabe: "ب", fr: "Lettre Baa", es: "Letra Baa", audio: "audio/02-baa.mp3" },
    { id: 3, type: "letter", arabe: "ت", fr: "Lettre Taa", es: "Letra Taa", audio: "audio/03-taa.mp3" },
    { id: 4, type: "letter", arabe: "ث", fr: "Lettre Thaa", es: "Letra Thaa", audio: "audio/04-thaa.mp3" },
    { id: 5, type: "letter", arabe: "ج", fr: "Lettre Jiim", es: "Letra Jiim", audio: "audio/05-jim.mp3" },
    { id: 6, type: "letter", arabe: "ح", fr: "Lettre Haa", es: "Letra Haa", audio: "audio/06-haa.mp3" },
    { id: 7, type: "letter", arabe: "خ", fr: "Lettre Khaa", es: "Letra Khaa", audio: "audio/07-khaa.mp3" },
    { id: 8, type: "letter", arabe: "د", fr: "Lettre Daal", es: "Letra Daal", audio: "audio/08-dal.mp3" },
    { id: 9, type: "letter", arabe: "ذ", fr: "Lettre Dhaal", es: "Letra Dhaal", audio: "audio/09-dhal.mp3" },
    { id: 10, type: "letter", arabe: "ر", fr: "Lettre Raa", es: "Letra Raa", audio: "audio/10-raa.mp3" },
    { id: 11, type: "letter", arabe: "ز", fr: "Lettre Zaay", es: "Letra Zaay", audio: "audio/11-zay.mp3" },
    { id: 12, type: "letter", arabe: "س", fr: "Lettre Siin", es: "Letra Siin", audio: "audio/12-siin.mp3" },
    { id: 13, type: "letter", arabe: "ش", fr: "Lettre Shiin", es: "Letra Shiin", audio: "audio/13-shiin.mp3" },
    { id: 14, type: "letter", arabe: "ص", fr: "Lettre Saad", es: "Letra Saad", audio: "audio/14-saad.mp3" },
    { id: 15, type: "letter", arabe: "ض", fr: "Lettre Daad", es: "Letra Daad", audio: "audio/15-daad.mp3" },
    { id: 16, type: "letter", arabe: "ط", fr: "Lettre Taa", es: "Letra Taa", audio: "audio/16-taaa.mp3" },
    { id: 17, type: "letter", arabe: "ظ", fr: "Lettre Zaa", es: "Letra Zaa", audio: "audio/17-zaa.mp3" },
    { id: 18, type: "letter", arabe: "ع", fr: "Lettre Ayn", es: "Letra Ayn", audio: "audio/18-ayn.mp3" },
    { id: 19, type: "letter", arabe: "غ", fr: "Lettre Ghayn", es: "Letra Ghayn", audio: "audio/19-ghayn.mp3" },
    { id: 20, type: "letter", arabe: "ف", fr: "Lettre Faa", es: "Letra Faa", audio: "audio/20-faa.mp3" },
    { id: 21, type: "letter", arabe: "ق", fr: "Lettre Qaaf", es: "Letra Qaaf", audio: "audio/21-qaaf.mp3" },
    { id: 22, type: "letter", arabe: "ك", fr: "Lettre Kaaf", es: "Letra Kaaf", audio: "audio/22-kaaf.mp3" },
    { id: 23, type: "letter", arabe: "ل", fr: "Lettre Laam", es: "Letra Laam", audio: "audio/23-laam.mp3" },
    { id: 24, type: "letter", arabe: "م", fr: "Lettre Miim", es: "Letra Miim", audio: "audio/24-miim.mp3" },
    { id: 25, type: "letter", arabe: "ن", fr: "Lettre Nuun", es: "Letra Nuun", audio: "audio/25-nuun.mp3" },
    { id: 26, type: "letter", arabe: "ه", fr: "Lettre Haa", es: "Letra Haa", audio: "audio/26-haaa.mp3" },
    { id: 27, type: "letter", arabe: "و", fr: "Lettre Waaw", es: "Letra Waaw", audio: "audio/27-waaw.mp3" },
    { id: 28, type: "letter", arabe: "ي", fr: "Lettre Yaa", es: "Letra Yaa", audio: "audio/28-yaa.mp3" },

    // VOCABULAIRE BASE MODULE 1 (29-100)
    { id: 29, type: "word", arabe: "أَسَد", icon: "fa-solid fa-paw", fr: "Lion", es: "León", audio: "audio/asad.mp3" },
    { id: 30, type: "word", arabe: "كَأْس", icon: "fa-solid fa-glass-water", fr: "Verre", es: "Vaso", audio: "audio/kas.mp3" },
    { id: 31, type: "word", arabe: "مَلْجَأ", icon: "fa-solid fa-house-chimney", fr: "Refuge", es: "Refugio", audio: "audio/malja.mp3" },
    { id: 32, type: "word", arabe: "بَاب", icon: "fa-solid fa-door-closed", fr: "Porte", es: "Puerta", audio: "audio/bab.mp3" },
    { id: 33, type: "word", arabe: "كَبِير", icon: "fa-solid fa-arrow-up-right-dots", fr: "Grand", es: "Grande", audio: "audio/kabir.mp3" },
    { id: 34, type: "word", arabe: "كِتَاب", icon: "fa-solid fa-book", fr: "Livre", es: "Libro", audio: "audio/kitab.mp3" },
    { id: 35, type: "word", arabe: "تَمْر", icon: "fa-solid fa-seedling", fr: "Datte", es: "Dátil", audio: "audio/tamr.mp3" },
    { id: 36, type: "word", arabe: "بَيْت", icon: "fa-solid fa-house", fr: "Maison", es: "Casa", audio: "audio/bayt.mp3" },
    { id: 37, type: "word", arabe: "ثَوْب", icon: "fa-solid fa-shirt", fr: "Vêtement", es: "Ropa", audio: "audio/thawb.mp3" },
    { id: 38, type: "word", arabe: "مَثَل", icon: "fa-solid fa-lightbulb", fr: "Exemple", es: "Ejemplo", audio: "audio/mathal.mp3" },
    { id: 39, type: "word", arabe: "بَحَث", icon: "fa-solid fa-magnifying-glass", fr: "Recherche", es: "Búsqueda", audio: "audio/bahath.mp3" },
    { id: 40, type: "word", arabe: "جَمَل", icon: "fa-solid fa-sun", fr: "Chameau", es: "Camello", audio: "audio/jamal.mp3" },
    { id: 41, type: "word", arabe: "رَجُل", icon: "fa-solid fa-user", fr: "Homme", es: "Hombre", audio: "audio/rajul.mp3" },
    { id: 42, type: "word", arabe: "بُرْج", icon: "fa-solid fa-chess-rook", fr: "Tour", es: "Torre", audio: "audio/burj.mp3" },
    { id: 43, type: "word", arabe: "حَبْل", icon: "fa-solid fa-link", fr: "Corde", es: "Cuerda", audio: "audio/habl.mp3" },
    { id: 44, type: "word", arabe: "بَحْر", icon: "fa-solid fa-water", fr: "Mer", es: "Mar", audio: "audio/bahr.mp3" },
    { id: 45, type: "word", arabe: "مِفْتَاح", icon: "fa-solid fa-key", fr: "Clé", es: "Llave", audio: "audio/miftah.mp3" },
    { id: 46, type: "word", arabe: "خُبْز", icon: "fa-solid fa-bread-slice", fr: "Pain", es: "Pan", audio: "audio/khobz.mp3" },
    { id: 47, type: "word", arabe: "نَخْل", icon: "fa-solid fa-tree", fr: "Palmier", es: "Palmera", audio: "audio/nakhl.mp3" },
    { id: 48, type: "word", arabe: "مَطْبَخ", icon: "fa-solid fa-kitchen-set", fr: "Cuisine", es: "Cocina", audio: "audio/matbakh.mp3" },
    { id: 49, type: "word", arabe: "دُب", icon: "fa-solid fa-paw", fr: "Ours", es: "Oso", audio: "audio/dub.mp3" },
    { id: 50, type: "word", arabe: "مَدْرَسَة", icon: "fa-solid fa-school", fr: "École", es: "Escuela", audio: "audio/madrasa.mp3" },
    { id: 51, type: "word", arabe: "وَلَد", icon: "fa-solid fa-child", fr: "Garçon", es: "Niño", audio: "audio/walad.mp3" },
    { id: 52, type: "word", arabe: "ذَهَب", icon: "fa-solid fa-coins", fr: "Or", es: "Oro", audio: "audio/dhahab.mp3" },
    { id: 53, type: "word", arabe: "هَذَا", icon: "fa-solid fa-hand-point-left", fr: "Ceci", es: "Esto", audio: "audio/hadha.mp3" },
    { id: 54, type: "word", arabe: "لَذِيذ", icon: "fa-solid fa-utensils", fr: "Délicieux", es: "Delicioso", audio: "audio/ladhidh.mp3" },
    { id: 55, type: "word", arabe: "وَرْدَة", icon: "fa-solid fa-leaf", fr: "Une rose", es: "Una rosa", audio: "audio/warda.mp3" },
    { id: 56, type: "word", arabe: "قَمَر", icon: "fa-solid fa-moon", fr: "Lune", es: "Luna", audio: "audio/qamar.mp3" },
    { id: 57, type: "word", arabe: "زَيْت", icon: "fa-solid fa-bottle-droplet", fr: "Huile", es: "Aceite", audio: "audio/zayt.mp3" },
    { id: 58, type: "word", arabe: "مَوْزَة", icon: "fa-solid fa-lemon", fr: "Une banane", es: "Un plátano", audio: "audio/mawza.mp3" },
    { id: 59, type: "word", arabe: "سَمَك", icon: "fa-solid fa-fish", fr: "Poisson", es: "Pescado", audio: "audio/samak.mp3" },
    { id: 60, type: "word", arabe: "مَسْجِد", icon: "fa-solid fa-mosque", fr: "Mosquée", es: "Mezquita", audio: "audio/masjid.mp3" },
    { id: 61, type: "word", arabe: "دَرْس", icon: "fa-solid fa-book-open", fr: "Leçon", es: "Lección", audio: "audio/dars.mp3" },
    { id: 62, type: "word", arabe: "شَمْس", icon: "fa-solid fa-sun", fr: "Soleil", es: "Sol", audio: "audio/shams.mp3" },
    { id: 63, type: "word", arabe: "مِشْمِش", icon: "fa-solid fa-apple-whole", fr: "Abricot", es: "Albaricoque", audio: "audio/mishmish.mp3" },
    { id: 64, type: "word", arabe: "عَرْش", icon: "fa-solid fa-chair", fr: "Trône", es: "Trono", audio: "audio/arsh.mp3" },
    { id: 65, type: "word", arabe: "صَبْر", icon: "fa-solid fa-hourglass-half", fr: "Patience", es: "Paciencia", audio: "audio/sabr.mp3" },
    { id: 66, type: "word", arabe: "بَصِير", icon: "fa-solid fa-eye", fr: "Clairvoyant", es: "Vidente", audio: "audio/basir.mp3" },
    { id: 67, type: "word", arabe: "نَص", icon: "fa-solid fa-file-lines", fr: "Texte", es: "Texto", audio: "audio/nass.mp3" },
    { id: 68, type: "word", arabe: "ضَوْء", icon: "fa-solid fa-lightbulb", fr: "Lumière", es: "Luz", audio: "audio/daw.mp3" },
    { id: 69, type: "word", arabe: "مَرِيض", icon: "fa-solid fa-bed-pulse", fr: "Malade", es: "Enfermo", audio: "audio/marid.mp3" },
    { id: 70, type: "word", arabe: "أَرْض", icon: "fa-solid fa-globe", fr: "Terre", es: "Tierra", audio: "audio/ard.mp3" },
    { id: 71, type: "word", arabe: "طِين", icon: "fa-solid fa-jar", fr: "Argile", es: "Arcilla", audio: "audio/tin.mp3" },
    { id: 72, type: "word", arabe: "مَطَر", icon: "fa-solid fa-cloud-rain", fr: "Pluie", es: "Lluvia", audio: "audio/matar.mp3" },
    { id: 73, type: "word", arabe: "قِط", icon: "fa-solid fa-cat", fr: "Chat", es: "Gato", audio: "audio/qitt.mp3" },
    { id: 74, type: "word", arabe: "ظِل", icon: "fa-solid fa-cloud", fr: "Ombre", es: "Sombra", audio: "audio/zill.mp3" },
    { id: 75, type: "word", arabe: "عَظِيم", icon: "fa-solid fa-mountain", fr: "Immense", es: "Grandioso", audio: "audio/azim.mp3" },
    { id: 76, type: "word", arabe: "حَظ", icon: "fa-solid fa-clover", fr: "Chance", es: "Suerte", audio: "audio/haz.mp3" },
    { id: 77, type: "word", arabe: "عَيْن", icon: "fa-solid fa-eye", fr: "Œil", es: "Ojo", audio: "audio/ayn.mp3" },
    { id: 78, type: "word", arabe: "مَلْعَب", icon: "fa-solid fa-futbol", fr: "Stade", es: "Estadio", audio: "audio/malab.mp3" },
    { id: 79, type: "word", arabe: "جَمْع", icon: "fa-solid fa-users", fr: "Groupe", es: "Grupo", audio: "audio/jam.mp3" },
    { id: 80, type: "word", arabe: "غَيْم", icon: "fa-solid fa-cloud", fr: "Nuage", es: "Nube", audio: "audio/ghaym.mp3" },
    { id: 81, type: "word", arabe: "مَغْرِب", icon: "fa-solid fa-map-location-dot", fr: "Maroc", es: "Marruecos", audio: "audio/maghrib.mp3" },
    { id: 82, type: "word", arabe: "صِبْغ", icon: "fa-solid fa-palette", fr: "Teinture", es: "Tinte", audio: "audio/sibgh.mp3" },
    { id: 83, type: "word", arabe: "فِيل", icon: "fa-solid fa-paw", fr: "Éléphant", es: "Elefante", audio: "audio/fil.mp3" },
    { id: 84, type: "word", arabe: "صَيْف", icon: "fa-solid fa-umbrella-beach", fr: "Été", es: "Verano", audio: "audio/sayf.mp3" },
    { id: 85, type: "word", arabe: "بَقَرَة", icon: "fa-solid fa-cow", fr: "Vache", es: "Vaca", audio: "audio/baqara.mp3" },
    { id: 86, type: "word", arabe: "سُوق", icon: "fa-solid fa-shop", fr: "Marché", es: "Mercado", audio: "audio/suq.mp3" },
    { id: 87, type: "word", arabe: "مَكْتَبَة", icon: "fa-solid fa-book", fr: "Bibliothèque", es: "Biblioteca", audio: "audio/maktaba.mp3" },
    { id: 88, type: "word", arabe: "لَبَن", icon: "fa-solid fa-glass-water", fr: "Lait", es: "Leche", audio: "audio/laban.mp3" },
    { id: 89, type: "word", arabe: "قَلَم", icon: "fa-solid fa-pen", fr: "Stylo", es: "Bolígrafo", audio: "audio/qalam.mp3" },
    { id: 90, type: "word", arabe: "جَبَل", icon: "fa-solid fa-mountain", fr: "Montagne", es: "Montaña", audio: "audio/jabal.mp3" },
    { id: 91, type: "word", arabe: "مَاء", icon: "fa-solid fa-droplet", fr: "Eau", es: "Agua", audio: "audio/ma.mp3" },
    { id: 92, type: "word", arabe: "نَجْم", icon: "fa-solid fa-star", fr: "Étoile", es: "Estrella", audio: "audio/najm.mp3" },
    { id: 93, type: "word", arabe: "عِنَب", icon: "fa-solid fa-leaf", fr: "Raisin", es: "Uvas", audio: "audio/inab.mp3" },
    { id: 94, type: "word", arabe: "هِلَال", icon: "fa-solid fa-moon", fr: "Lune", es: "Media luna", audio: "audio/hilal.mp3" },
    { id: 95, type: "word", arabe: "نَهْر", icon: "fa-solid fa-water", fr: "Rivière", es: "Río", audio: "audio/nahr.mp3" },
    { id: 96, type: "word", arabe: "وَجْه", icon: "fa-solid fa-face-smile", fr: "Visage", es: "Rostro", audio: "audio/wajh.mp3" },
    { id: 97, type: "word", arabe: "وَرْد", icon: "fa-solid fa-spa", fr: "Roses", es: "Rosas", audio: "audio/ward.mp3" },
    { id: 98, type: "word", arabe: "قَوْس", icon: "fa-solid fa-bullseye", fr: "Arc", es: "Arco", audio: "audio/qaws.mp3" },
    { id: 99, type: "word", arabe: "يَد", icon: "fa-solid fa-hand", fr: "Main", es: "Mano", audio: "audio/yad.mp3" },
    { id: 100, type: "word", arabe: "كُرْسِي", icon: "fa-solid fa-chair", fr: "Chaise", es: "Silla", audio: "audio/kursi.mp3" },

    // NOUVEAUX MOTS DU MODULE 2 (QUIZ 2 & 3) (101-168)
    { id: 101, type: "word", arabe: "دَعَ", icon: "fa-solid fa-hand-holding", fr: "Laisse", es: "Deja", audio: "audio/module2/daa.mp3" },
    { id: 102, type: "word", arabe: "رَأَ", icon: "fa-solid fa-eye", fr: "A vu", es: "Vio", audio: "audio/module2/raa.mp3" },
    { id: 103, type: "word", arabe: "مَعَ", icon: "fa-solid fa-people-arrows", fr: "Avec", es: "Con", audio: "audio/module2/maa.mp3" },
    { id: 104, type: "word", arabe: "لَكَ", icon: "fa-solid fa-hand-holding-heart", fr: "À toi", es: "Para ti", audio: "audio/module2/laka.mp3" },
    { id: 105, type: "word", arabe: "نَمَ", icon: "fa-solid fa-bed", fr: "A dormi", es: "Durmió", audio: "audio/module2/nama.mp3" },
    { id: 106, type: "word", arabe: "بَدَ", icon: "fa-solid fa-bolt", fr: "Est apparu", es: "Apareció", audio: "audio/module2/bada.mp3" },
    { id: 107, type: "word", arabe: "هَبَ", icon: "fa-solid fa-gift", fr: "Donne", es: "Da", audio: "audio/module2/haba.mp3" },
    { id: 108, type: "word", arabe: "سَرَ", icon: "fa-solid fa-person-walking", fr: "A marché", es: "Caminó", audio: "audio/module2/sara.mp3" },
    { id: 109, type: "word", arabe: "قَدَ", icon: "fa-solid fa-compass", fr: "A dirigé", es: "Dirigió", audio: "audio/module2/qada.mp3" },
    { id: 110, type: "word", arabe: "كَمَ", icon: "fa-solid fa-circle-question", fr: "Combien", es: "Cuánto", audio: "audio/module2/kama.mp3" },
    { id: 111, type: "word", arabe: "هَلَ", icon: "fa-solid fa-question", fr: "Est-ce que", es: "Acaso", audio: "audio/module2/hala.mp3" },
    { id: 112, type: "word", arabe: "قُمْ", icon: "fa-solid fa-person-arrow-up-from-line", fr: "Lève-toi", es: "Levántate", audio: "audio/module2/qum.mp3" },
    { id: 113, type: "word", arabe: "خُذْ", icon: "fa-solid fa-hand-holding", fr: "Prends", es: "Toma", audio: "audio/module2/khudh.mp3" },
    { id: 114, type: "word", arabe: "كُلْ", icon: "fa-solid fa-utensils", fr: "Mange", es: "Come", audio: "audio/module2/kul.mp3" },
    { id: 115, type: "word", arabe: "هُمْ", icon: "fa-solid fa-users", fr: "Ils", es: "Ellos", audio: "audio/module2/hum.mp3" },
    { id: 116, type: "word", arabe: "لَهُ", icon: "fa-solid fa-hand-holding-hand", fr: "À lui", es: "Para él", audio: "audio/module2/lahu.mp3" },
    { id: 117, type: "word", arabe: "غُضْ", icon: "fa-solid fa-arrow-down", fr: "Baisse", es: "Baja", audio: "audio/module2/ghudh.mp3" },
    { id: 118, type: "word", arabe: "شُدْ", icon: "fa-solid fa-arrows-left-right", fr: "Tire", es: "Tira", audio: "audio/module2/shud.mp3" },
    { id: 119, type: "word", arabe: "عُدْ", icon: "fa-solid fa-rotate-left", fr: "Reviens", es: "Vuelve", audio: "audio/module2/ud.mp3" },
    { id: 120, type: "word", arabe: "زُمْ", icon: "fa-solid fa-compress", fr: "Serre", es: "Aprieta", audio: "audio/module2/zum.mp3" },
    { id: 121, type: "word", arabe: "غُلْ", icon: "fa-solid fa-link-slash", fr: "Trahison", es: "Traición", audio: "audio/module2/ghul.mp3" },
    { id: 122, type: "word", arabe: "رُجْ", icon: "fa-solid fa-shake", fr: "Secoue", es: "Agita", audio: "audio/module2/ruj.mp3" },
    { id: 123, type: "word", arabe: "سُقْ", icon: "fa-solid fa-car", fr: "Conduis", es: "Conduce", audio: "audio/module2/suq.mp3" },
    { id: 124, type: "word", arabe: "طُفْ", icon: "fa-solid fa-rotate", fr: "Tourne", es: "Gira", audio: "audio/module2/tuf.mp3" },
    { id: 125, type: "word", arabe: "بِتْ", icon: "fa-solid fa-moon", fr: "Passe la nuit", es: "Pasa la noche", audio: "audio/module2/bit.mp3" },
    { id: 126, type: "word", arabe: "سِرْ", icon: "fa-solid fa-person-walking", fr: "Marche", es: "Camina", audio: "audio/module2/sir.mp3" },
    { id: 127, type: "word", arabe: "قِفْ", icon: "fa-solid fa-hand", fr: "Arrête-toi", es: "Detente", audio: "audio/module2/qif.mp3" },
    { id: 128, type: "word", arabe: "صِفْ", icon: "fa-solid fa-pen-clip", fr: "Décris", es: "Describe", audio: "audio/module2/sif.mp3" },
    { id: 129, type: "word", arabe: "زِدْ", icon: "fa-solid fa-plus", fr: "Ajoute", es: "Añade", audio: "audio/module2/zid.mp3" },
    { id: 130, type: "word", arabe: "كِدْ", icon: "fa-solid fa-mask", fr: "Ruse", es: "Engaña", audio: "audio/module2/kid.mp3" },
    { id: 131, type: "word", arabe: "دِنْ", icon: "fa-solid fa-gavel", fr: "Juge", es: "Juzga", audio: "audio/module2/din.mp3" },
    { id: 132, type: "word", arabe: "غِبْ", icon: "fa-solid fa-user-minus", fr: "Absente-toi", es: "Auséntate", audio: "audio/module2/ghib.mp3" },
    { id: 133, type: "word", arabe: "طِبْ", icon: "fa-solid fa-heart", fr: "Sois bon", es: "Sé bueno", audio: "audio/module2/tib.mp3" },
    { id: 134, type: "word", arabe: "شِفْ", icon: "fa-solid fa-staff-snake", fr: "Guéris", es: "Sana", audio: "audio/module2/shif.mp3" },
    { id: 135, type: "word", arabe: "بِكَ", icon: "fa-solid fa-user-check", fr: "Par toi", es: "Por ti", audio: "audio/module2/bika.mp3" },
    { id: 136, type: "word", arabe: "بِهِ", icon: "fa-solid fa-user-check", fr: "Par lui", es: "Por él", audio: "audio/module2/bihi.mp3" },
    { id: 137, type: "word", arabe: "صُمْ", icon: "fa-solid fa-star-and-crescent", fr: "Jeûne", es: "Ayuna", audio: "audio/module2/sum.mp3" },
    { id: 138, type: "word", arabe: "مُتْ", icon: "fa-solid fa-skull", fr: "Meurs", es: "Muere", audio: "audio/module2/mut.mp3" },
    { id: 139, type: "word", arabe: "أَبُ", icon: "fa-solid fa-person-cane", fr: "Père", es: "Padre", audio: "audio/module2/abu.mp3" },
    { id: 140, type: "word", arabe: "أَخُ", icon: "fa-solid fa-user-group", fr: "Frère", es: "Hermano", audio: "audio/module2/akhu.mp3" },
    { id: 141, type: "word", arabe: "دَمُ", icon: "fa-solid fa-droplet", fr: "Sang", es: "Sangre", audio: "audio/module2/damu.mp3" },
    { id: 142, type: "word", arabe: "فَمُ", icon: "fa-solid fa-teeth-open", fr: "Bouche", es: "Boca", audio: "audio/module2/famu.mp3" },
    { id: 143, type: "word", arabe: "مَنْ", icon: "fa-solid fa-person-circle-question", fr: "Qui", es: "Quién", audio: "audio/module2/man.mp3" },
    { id: 144, type: "word", arabe: "بَلْ", icon: "fa-solid fa-code-merge", fr: "Mais", es: "Pero", audio: "audio/module2/bal.mp3" },
    { id: 145, type: "word", arabe: "عَنْ", icon: "fa-solid fa-arrow-right-from-bracket", fr: "De", es: "De", audio: "audio/module2/an.mp3" },
    { id: 146, type: "word", arabe: "قَدْ", icon: "fa-solid fa-check-double", fr: "Certes", es: "Ciertamente", audio: "audio/module2/qad.mp3" },
    { id: 147, type: "word", arabe: "لَمْ", icon: "fa-solid fa-ban", fr: "Ne pas", es: "No", audio: "audio/module2/lam.mp3" },
    { id: 148, type: "word", arabe: "لَنْ", icon: "fa-solid fa-xmark", fr: "Ne jamais", es: "Nunca", audio: "audio/module2/lan.mp3" },
    { id: 149, type: "word", arabe: "كَمْ", icon: "fa-solid fa-calculator", fr: "Combien", es: "Cuánto", audio: "audio/module2/kam.mp3" },
    { id: 150, type: "word", arabe: "كَتَبَ", icon: "fa-solid fa-pen", fr: "A écrit", es: "Escribió", audio: "audio/module2/kataba.mp3" },
    { id: 151, type: "word", arabe: "دَخَلَ", icon: "fa-solid fa-door-open", fr: "Est entré", es: "Entró", audio: "audio/module2/dakhala.mp3" },
    { id: 152, type: "word", arabe: "جَلَسَ", icon: "fa-solid fa-chair", fr: "S'est assis", es: "Se sentó", audio: "audio/module2/jalasa.mp3" },
    { id: 153, type: "word", arabe: "شَرِبَ", icon: "fa-solid fa-glass-water", fr: "A bu", es: "Bebió", audio: "audio/module2/shariba.mp3" },
    { id: 154, type: "word", arabe: "سَمِعَ", icon: "fa-solid fa-ear-listen", fr: "A entendu", es: "Escuchó", audio: "audio/module2/samia.mp3" },
    { id: 155, type: "word", arabe: "لَعِبَ", icon: "fa-solid fa-gamepad", fr: "A joué", es: "Jugó", audio: "audio/module2/laiba.mp3" },
    { id: 156, type: "word", arabe: "حَسُنَ", icon: "fa-solid fa-thumbs-up", fr: "Était bon", es: "Fue bueno", audio: "audio/module2/hasuna.mp3" },
    { id: 157, type: "word", arabe: "كَبُرَ", icon: "fa-solid fa-arrow-up-right-dots", fr: "A grandi", es: "Creció", audio: "audio/module2/kabura.mp3" },
    { id: 158, type: "word", arabe: "صَغُرَ", icon: "fa-solid fa-minimize", fr: "A rapetissé", es: "Achicó", audio: "audio/module2/saghura.mp3" },
    { id: 159, type: "word", arabe: "عَمِلَ", icon: "fa-solid fa-briefcase", fr: "A travaillé", es: "Trabajó", audio: "audio/module2/amila.mp3" },
    { id: 160, type: "word", arabe: "بِنْت", icon: "fa-solid fa-child-dress", fr: "Fille", es: "Niña", audio: "audio/module2/bint.mp3" },
    { id: 161, type: "word", arabe: "قَلْب", icon: "fa-solid fa-heart", fr: "Cœur", es: "Corazón", audio: "audio/module2/qalb.mp3" },
    { id: 162, type: "word", arabe: "أُذُن", icon: "fa-solid fa-ear-listen", fr: "Oreille", es: "Oreja", audio: "audio/module2/udhun.mp3" },
    { id: 163, type: "word", arabe: "رِجْل", icon: "fa-solid fa-shoe-prints", fr: "Jambe", es: "Pierna", audio: "audio/module2/rijl.mp3" },
    { id: 164, type: "word", arabe: "قِرْد", icon: "fa-solid fa-monkey", fr: "Singe", es: "Mono", audio: "audio/module2/qird.mp3" },
    { id: 165, type: "word", arabe: "ذِئْب", icon: "fa-solid fa-dog", fr: "Loup", es: "Lobo", audio: "audio/module2/dhib.mp3" },
    { id: 166, type: "word", arabe: "مَكْتَب", icon: "fa-solid fa-computer-desk", fr: "Bureau", es: "Escritorio", audio: "audio/module2/maktab.mp3" },
    { id: 167, type: "word", arabe: "مُسْلِم", icon: "fa-solid fa-person-praying", fr: "Musulman", es: "Musulmán", audio: "audio/module2/muslim.mp3" },
    { id: 168, type: "word", arabe: "دَفْتَر", icon: "fa-solid fa-book-open", fr: "Cahier", es: "Cuaderno", audio: "audio/module2/daftar.mp3" },

    // QUELQUES MOTS REPRÉSENTATIFS DU MODULE 3 (MODOUD) (169-178)
    { id: 169, type: "word", arabe: "تَاج", icon: "fa-solid fa-crown", fr: "Couronne", es: "Corona", audio: "audio/module3/taj.mp3" },
    { id: 170, type: "word", arabe: "حُوت", icon: "fa-solid fa-fish", fr: "Baleine", es: "Ballena", audio: "audio/module3/hut.mp3" },
    { id: 171, type: "word", arabe: "تِين", icon: "fa-solid fa-leaf", fr: "Figue", es: "Higo", audio: "audio/module3/tin.mp3" },
    { id: 172, type: "word", arabe: "سَاحَة", icon: "fa-solid fa-tree-city", fr: "Place / Cour", es: "Plaza", audio: "audio/module3/saha.mp3" },
    { id: 173, type: "word", arabe: "نُور", icon: "fa-solid fa-lightbulb", fr: "Lumière", es: "Luz", audio: "audio/module3/nur.mp3" },
    { id: 174, type: "word", arabe: "دِيك", icon: "fa-solid fa-crow", fr: "Coq", es: "Gallo", audio: "audio/module3/dik.mp3" },
    { id: 175, type: "word", arabe: "عَالِم", icon: "fa-solid fa-graduation-cap", fr: "Savant", es: "Erudito", audio: "audio/module3/alim.mp3" },
    { id: 176, type: "word", arabe: "سُوق", icon: "fa-solid fa-shop", fr: "Marché", es: "Mercado", audio: "audio/module3/suq.mp3" },
    { id: 177, type: "word", arabe: "طَبِيب", icon: "fa-solid fa-user-doctor", fr: "Médecin", es: "Médico", audio: "audio/module3/tabib.mp3" },
    { id: 178, type: "word", arabe: "حَقِيبَة", icon: "fa-solid fa-briefcase", fr: "Valise", es: "Maleta", audio: "audio/module3/haqiba.mp3" }
];
