(()=>{
"use strict";

const DATA = {

  /* ══════════════════════════════════ 1. مِنَ المُضَارِعِ إِلَى الأَمْرِ ══════════════════════════════════ */ fil: [
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="color:var(--green);">فِعْلُ الأَمْرِ</div> <div class="card-title-fr serif">L'IMPÉRATIF</div> <div class="card-title-es serif">EL IMPERATIVO</div> <div class="card-sep"></div> <div class="card-rule-fr">Tu connais déjà :</div> <div class="gabarit-box"> <div class="gabarit-ar ar" style="font-size:1.5rem;">اَلْمَاضِي ← اَلْمُضَارِع ← اَلْأَمْر</div> <div class="gabarit-ar ar" style="font-size:1.9rem;color:var(--green);margin-top:6px;">كَتَبَ ← يَكْتُبُ ← اُكْتُبْ</div> </div> <div class="card-rule-fr" style="text-align:center;">il a écrit → il écrit → <strong class="green">écris !</strong></div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Le point de départ · El punto de partida</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Le point de départ</div></div> <div class="card-sep"></div> <div style="background:rgba(200,164,98,0.08);border:1px solid rgba(200,164,98,0.3);border-radius:14px;padding:16px;text-align:center;"> <div style="font-family:'Amiri',serif;direction:rtl;font-size:1.1rem;color:var(--burgundy);font-weight:700;line-height:1.9;">نَنْطَلِقُ مِنَ الْمُضَارِعِ</div> <div style="font-size:0.82rem;color:var(--text-soft);margin-top:6px;">Pour construire correctement l'impératif, le <strong>présent</strong> est notre point de départ — pas le passé.<br><em>Para construir correctamente el imperativo, el <strong>presente</strong> es nuestro punto de partida.</em></div> </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Le وزن reste le guide · El patrón sigue siendo la guía</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">اَلْوَزْنُ يَبْقَى الدَّلِيل</div> <div class="card-title-fr serif">LE GABARIT RESTE LE GUIDE</div> <div class="card-title-es serif">EL PATRÓN SIGUE SIENDO LA GUÍA</div> <div class="card-sep"></div> <table class="conj-table"> <thead><tr><th>مَاضٍ</th><th>مُضَارِع</th><th>أَمْر</th></tr></thead> <tbody> <tr><td class="ct-ar ar ism">كَتَبَ</td><td class="ct-ar ar fil">يَكْتُبُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اُكْتُبْ</td></tr> <tr><td class="ct-ar ar ism">دَخَلَ</td><td class="ct-ar ar fil">يَدْخُلُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اُدْخُلْ</td></tr> </tbody> </table> <div class="card-rule-fr" style="font-size:0.85rem;">💡 Ces deux verbes viennent de la même famille : فَعَلَ → يَفْعُلُ (Module 17).</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Les 2 autres familles · Las otras 2 familias</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Les 2 autres familles</div></div> <div class="card-sep"></div> <table class="conj-table" style="font-size:0.78rem;"> <thead><tr><th>مَاضٍ</th><th>مُضَارِع</th><th>أَمْر</th></tr></thead> <tbody> <tr><td class="ct-ar ar ism">جَلَسَ</td><td class="ct-ar ar fil">يَجْلِسُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اِجْلِسْ</td></tr> <tr><td class="ct-ar ar ism">ضَرَبَ</td><td class="ct-ar ar fil">يَضْرِبُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اِضْرِبْ</td></tr> <tr><td class="ct-ar ar ism">فَتَحَ</td><td class="ct-ar ar fil">يَفْتَحُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اِفْتَحْ</td></tr> <tr><td class="ct-ar ar ism">ذَهَبَ</td><td class="ct-ar ar fil">يَذْهَبُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اِذْهَبْ</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Attention : pas de règle unique ! · ¡Atención!</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">اِنْتَبِهْ!</div> <div class="card-title-fr serif">ATTENTION !</div> <div class="card-title-es serif">¡ATENCIÓN!</div> <div class="card-sep"></div> <div class="card-rule-fr" style="text-align:center;font-weight:700;color:var(--burgundy);">« اَلْأَمْرُ = اِفْعَلْ » N'EST PAS une règle universelle !</div> <div style="text-align:center;font-family:'Amiri',serif;direction:rtl;font-size:1.3rem;color:var(--text-dark);margin-top:10px;line-height:2;"> يَكْتُبُ → <span style="color:#7b5ea7;font-weight:700;">اُكْتُبْ</span><br> يَجْلِسُ → <span style="color:#7b5ea7;font-weight:700;">اِجْلِسْ</span><br> يَفْتَحُ → <span style="color:#7b5ea7;font-weight:700;">اِفْتَحْ</span> </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Pourquoi ces différences ? · ¿Por qué estas diferencias?</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Pourquoi ces différences ?</div></div> <div class="card-sep"></div> <div class="card-rule-fr">L'objectif de ce module est justement de comprendre <strong>pourquoi</strong> l'impératif change selon la famille du verbe — exactement comme le présent (Module 17) a trois familles : يَفْعُلُ / يَفْعِلُ / يَفْعَلُ.</div> <div class="card-rule-es" style="margin-top:6px;">El objetivo de este módulo es entender por qué el imperativo cambia según la familia del verbo.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Je transforme · Yo transformo</div>`
    }
  ],

  /* ══════════════════════════════════ 2. أُحَوِّلُ — je transforme ══════════════════════════════════ */ madhi: [
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.5rem,5vw,2rem);">أُحَوِّلُ مِنْ أَنْتَ</div> <div class="card-title-fr serif">JE TRANSFORME DEPUIS أَنْتَ</div> <div class="card-title-es serif">TRANSFORMO DESDE أَنْتَ</div> <div class="card-sep"></div> <div class="card-rule-fr">Je pars du présent de أَنْتَ, la forme la plus simple pour découvrir l'impératif :</div> <div style="text-align:center;font-family:'Amiri',serif;direction:rtl;font-size:1.4rem;color:var(--burgundy);line-height:2.2;margin-top:8px;"> تَكْتُبُ<br>↓<br>تَكْتُبْ<br>↓<br>كْتُبْ<br>↓<br><strong style="color:var(--green);">اُكْتُبْ</strong> </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;D'autres verbes · Otros verbos</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">D'autres verbes</div></div> <div class="card-sep"></div> <table class="conj-table" style="font-size:0.78rem;"> <thead><tr><th>أَنْتَ (مُضَارِع)</th><th>اَلْأَمْر</th></tr></thead> <tbody> <tr><td class="ct-ar ar ism">تَجْلِسُ</td><td class="ct-ar ar fil">اِجْلِسْ</td></tr> <tr><td class="ct-ar ar ism">تَفْتَحُ</td><td class="ct-ar ar fil">اِفْتَحْ</td></tr> <tr><td class="ct-ar ar ism">تَدْخُلُ</td><td class="ct-ar ar fil">اُدْخُلْ</td></tr> </tbody> </table> <div class="card-rule-fr" style="margin-top:8px;font-size:0.85rem;">💡 Toujours le même mécanisme : j'enlève تَـ, puis j'ajoute la bonne voyelle de liaison.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Pourquoi اُ / اِ ? · ¿Por qué اُ / اِ?</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">لِمَاذَا اُ أَوْ اِ ؟</div> <div class="card-title-fr serif">POURQUOI اُ OU اِ ?</div> <div class="card-title-es serif">¿POR QUÉ اُ O اِ?</div> <div class="card-sep"></div> <div class="card-rule-fr">En arabe, un mot ne peut pas commencer par une lettre sans voyelle (كْتُبْ est impossible à prononcer seul). On ajoute donc une petite <strong>« lettre d'appui »</strong> : هَمْزَةُ الْوَصْلِ.</div> <div class="card-rule-es" style="margin-top:6px;">Una palabra no puede empezar por una letra sin vocal. Se añade una «letra de apoyo».</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Quelle voyelle choisir ? · ¿Qué vocal elegir?</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Quelle voyelle choisir ?</div></div> <div class="card-sep"></div> <div style="background:rgba(200,164,98,0.08);border:1px solid rgba(200,164,98,0.3);border-radius:14px;padding:14px;text-align:center;"> <div style="font-family:'Amiri',serif;direction:rtl;font-size:1rem;color:var(--burgundy);font-weight:700;line-height:1.9;">اُنْظُرْ إِلَى حَرَكَةِ الْمُضَارِعِ</div> <div style="font-size:0.8rem;color:var(--text-soft);margin-top:4px;">Je regarde la voyelle du présent (يَكْتُبُ, يَجْلِسُ...) :<br>• dhamma (ُ) → j'ajoute <strong>اُ</strong><br>• kasra (ِ) ou fatha (َ) → j'ajoute <strong>اِ</strong></div> </div> <table class="conj-table" style="margin-top:8px;font-size:0.76rem;"> <thead><tr><th>مُضَارِع</th><th>أَمْر</th></tr></thead> <tbody> <tr><td class="ct-ar ar fil">يَكْتُبُ (ُ)</td><td class="ct-ar ar" style="color:#7b5ea7;">اُكْتُبْ</td></tr> <tr><td class="ct-ar ar fil">يَجْلِسُ (ِ)</td><td class="ct-ar ar" style="color:#7b5ea7;">اِجْلِسْ</td></tr> <tr><td class="ct-ar ar fil">يَفْتَحُ (َ)</td><td class="ct-ar ar" style="color:#7b5ea7;">اِفْتَحْ</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Le gabarit de l'impératif · El patrón del imperativo</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">تَذَكَّرْ يَذْهَبُ</div> <div class="card-title-fr serif">RAPPEL : يَذْهَبُ</div> <div class="card-title-es serif">RECORDATORIO: يَذْهَبُ</div> <div class="card-sep"></div> <div style="text-align:center;font-family:'Amiri',serif;direction:rtl;font-size:1.4rem;color:var(--burgundy);line-height:2.2;"> تَذْهَبُ<br>↓<br>تَذْهَبْ<br>↓<br>ذْهَبْ<br>↓<br><strong style="color:var(--green);">اِذْهَبْ</strong> </div> <div class="card-rule-fr" style="margin-top:8px;font-size:0.85rem;">فَتَحَ (fatha) → يَفْتَحُ (fatha) → hamza <strong>اِ</strong></div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Le gabarit de l'impératif · El patrón del imperativo</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Récapitulatif</div></div> <div class="card-sep"></div> <div class="card-rule-fr" style="text-align:center;font-weight:700;color:var(--burgundy);">مُضَارِع ← أَمْر</div> <div style="text-align:center;font-family:'Amiri',serif;direction:rtl;font-size:1.1rem;color:var(--text-dark);margin-top:8px;line-height:2;"> تَكْتُبُ ← اُكْتُبْ<br> تَجْلِسُ ← اِجْلِسْ<br> تَفْتَحُ ← اِفْتَحْ<br> تَدْخُلُ ← اُدْخُلْ<br> تَذْهَبُ ← اِذْهَبْ </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;وَزْنُ الأَمْر</div>`
    }
  ],

  /* ══════════════════════════════════ 3. وَزْنُ الأَمْرِ — le gabarit de l'impératif ══════════════════════════════════ */ mudhari: [
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">وَزْنُ الأَمْرِ</div> <div class="card-title-fr serif">LE GABARIT DE L'IMPÉRATIF</div> <div class="card-title-es serif">EL PATRÓN DEL IMPERATIVO</div> <div class="card-sep"></div> <div style="text-align:center;font-family:'Amiri',serif;direction:rtl;font-size:1.3rem;font-weight:700;line-height:2.1;"> <span style="color:#C8A462;">يَفْعُلُ</span> ← <span style="color:#7b5ea7;">اُفْعُلْ</span><br> <span class="ex-fr" style="font-size:0.8rem;font-family:Montserrat,sans-serif;">يَكْتُبُ ← اُكْتُبْ</span> </div> <div class="card-sep"></div> <div style="text-align:center;font-family:'Amiri',serif;direction:rtl;font-size:1.3rem;font-weight:700;line-height:2.1;"> <span style="color:#C8A462;">يَفْعِلُ</span> ← <span style="color:#7b5ea7;">اِفْعِلْ</span><br> <span class="ex-fr" style="font-size:0.8rem;font-family:Montserrat,sans-serif;">يَجْلِسُ ← اِجْلِسْ</span> </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;La 3ᵉ famille · La 3ª familia</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">La 3ᵉ famille</div></div> <div class="card-sep"></div> <div style="text-align:center;font-family:'Amiri',serif;direction:rtl;font-size:1.3rem;font-weight:700;line-height:2.1;"> <span style="color:#C8A462;">يَفْعَلُ</span> ← <span style="color:#7b5ea7;">اِفْعَلْ</span><br> <span class="ex-fr" style="font-size:0.8rem;font-family:Montserrat,sans-serif;">يَفْتَحُ ← اِفْتَحْ</span> </div> <div class="card-rule-fr" style="margin-top:10px;font-size:0.85rem;">💡 <strong>ف ↔ 1ʳᵉ lettre · ع ↔ 2ᵉ lettre · ل ↔ 3ᵉ lettre.</strong> Ainsi le Module 18 clôt la progression : فَعَلَ (M16) → يَفْعُلُ/يَفْعِلُ/يَفْعَلُ (M17) → اُفْعُلْ/اِفْعِلْ/اِفْعَلْ (M18) !</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Le réflexe DAK · El reflejo DAK</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.2rem,4vw,1.6rem);">أُرَاقِبُ ← أَزِنُ ← أُحَوِّلُ ← أَبْنِي ← أَفْهَمُ</div> <div class="card-title-fr serif">LE RÉFLEXE DAK</div> <div class="card-title-es serif">EL REFLEJO DAK</div> <div class="card-sep"></div> <div style="font-family:'Amiri',serif;direction:rtl;font-size:0.92rem;color:var(--burgundy);line-height:2.1;text-align:center;"> ١ أُرَاقِبُ : <span style="color:var(--gold);">تَكْتُبُ</span><br> ٢ أَزِنُ : يَفْعُلُ<br> ٣ أُحَوِّلُ : تَكْتُبُ → تَكْتُبْ<br> ٤ أَبْنِي : <strong style="color:var(--green);">اُكْتُبْ</strong><br> ٥ أَفْهَمُ : Écris ! </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;À qui je parle ? · ¿A quién hablo?</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Ce mécanisme revient toujours</div></div> <div class="card-sep"></div> <div class="card-rule-fr" style="text-align:center;">J'observe → je pèse → je transforme → je construis → je comprends. Ce réflexe va revenir plusieurs fois dans la leçon, avec plusieurs verbes.</div> <div class="card-rule-es" style="text-align:center;margin-top:6px;">Observo → peso → transformo → construyo → comprendo.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;À qui je parle ? · ¿A quién hablo?</div>`
    }
  ],

  /* ══════════════════════════════════ 4. إِلَى مَنْ أَتَحَدَّثُ؟ ══════════════════════════════════ */ amr: [
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">إِلَى مَنْ أَتَحَدَّثُ؟</div> <div class="card-title-fr serif">À QUI JE PARLE ?</div> <div class="card-title-es serif">¿A QUIÉN HABLO?</div> <div class="card-sep"></div> <div class="card-rule-fr">فِعْلُ الأَمْرِ s'adresse toujours directement à <strong>toi</strong> — rappelle-toi les pronoms du <strong>Module 15</strong> :</div> <table class="conj-table"> <thead><tr><th>ضَمِير</th><th>أَمْر (كَتَبَ)</th></tr></thead> <tbody> <tr><td class="ct-pron ar">أَنْتَ</td><td class="ct-ar ar fil">اُكْتُبْ</td></tr> <tr><td class="ct-pron ar">أَنْتِ</td><td class="ct-ar ar fil">اُكْتُبِي</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Les formes du groupe · Las formas del grupo</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Les formes du groupe</div></div> <div class="card-sep"></div> <table class="conj-table" style="font-size:0.8rem;"> <thead><tr><th>ضَمِير</th><th>أَمْر (كَتَبَ)</th></tr></thead> <tbody> <tr><td class="ct-pron ar">أَنْتُمَا</td><td class="ct-ar ar fil">اُكْتُبَا</td></tr> <tr><td class="ct-pron ar">أَنْتُمْ</td><td class="ct-ar ar fil">اُكْتُبُوا</td></tr> <tr><td class="ct-pron ar">أَنْتُنَّ</td><td class="ct-ar ar fil">اُكْتُبْنَ</td></tr> </tbody> </table> <div class="card-rule-fr" style="margin-top:8px;font-size:0.85rem;">💡 On ne dit jamais « أَنَا اُكْتُبْ » — l'impératif n'a PAS de forme pour أنا/هو/هي. Il s'adresse toujours directement à quelqu'un.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Je décompose · Descompongo</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">أُفَكِّكُ الشَّكْل</div> <div class="card-title-fr serif">JE DÉCOMPOSE LA FORME</div> <div class="card-title-es serif">DESCOMPONGO LA FORMA</div> <div class="card-sep"></div> <div class="gabarit-box"> <div class="gabarit-ar ar" style="font-size:1.5rem;">اُكْتُبِي = اُكْتُبْ + ي</div> <div class="gabarit-label serif">أَنْتِ</div> </div> <div class="gabarit-box"> <div class="gabarit-ar ar" style="font-size:1.5rem;">اُكْتُبُوا = اُكْتُبْ + وا</div> <div class="gabarit-label serif">أَنْتُمْ</div> </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;أَنْتُنَّ · Vosotras</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">أَنْتُنَّ</div></div> <div class="card-sep"></div> <div class="gabarit-box"> <div class="gabarit-ar ar" style="font-size:1.5rem;">اُكْتُبْنَ</div> <div class="gabarit-label serif">forme propre à أَنْتُنَّ — comme au présent (Module 17)</div> </div> <div class="card-rule-fr" style="margin-top:8px;font-size:0.82rem;">💡 La marque ـي correspond à أَنْتِ, ـوا à أَنْتُمْ. Pour أَنْتُنَّ, c'est la forme entière اُكْتُبْنَ qui se reconnaît d'un coup — comme au présent, où تَكْتُبْنَ ne se décompose pas non plus.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Transfert : دَخَلَ وَجَلَسَ · Transferencia</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.5rem,5vw,2rem);">دَخَلَ وَجَلَسَ</div> <div class="card-title-fr serif">TRANSFERT : دَخَلَ وَجَلَسَ</div> <div class="card-title-es serif">TRANSFERENCIA</div> <div class="card-sep"></div> <table class="conj-table"> <thead><tr><th>ضَمِير</th><th>اُدْخُلْ</th><th>اِجْلِسْ</th></tr></thead> <tbody> <tr><td class="ct-pron ar">أَنْتَ</td><td class="ct-ar ar fil">اُدْخُلْ</td><td class="ct-ar ar fil">اِجْلِسْ</td></tr> <tr><td class="ct-pron ar">أَنْتِ</td><td class="ct-ar ar fil">اُدْخُلِي</td><td class="ct-ar ar fil">اِجْلِسِي</td></tr> <tr><td class="ct-pron ar">أَنْتُمْ</td><td class="ct-ar ar fil">اُدْخُلُوا</td><td class="ct-ar ar fil">اِجْلِسُوا</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;ضَرَبَ وَفَتَحَ · Transferencia</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">ضَرَبَ وَفَتَحَ</div></div> <div class="card-sep"></div> <table class="conj-table"> <thead><tr><th>ضَمِير</th><th>اِضْرِبْ</th><th>اِفْتَحْ</th></tr></thead> <tbody> <tr><td class="ct-pron ar">أَنْتَ</td><td class="ct-ar ar fil">اِضْرِبْ</td><td class="ct-ar ar fil">اِفْتَحْ</td></tr> <tr><td class="ct-pron ar">أَنْتِ</td><td class="ct-ar ar fil">اِضْرِبِي</td><td class="ct-ar ar fil">اِفْتَحِي</td></tr> <tr><td class="ct-pron ar">أَنْتُمْ</td><td class="ct-ar ar fil">اِضْرِبُوا</td><td class="ct-ar ar fil">اِفْتَحُوا</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;ذَهَبَ · Y ذَهَبَ</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.6rem,5.5vw,2.2rem);">اِذْهَبْ</div> <div class="card-title-fr serif">ذَهَبَ À L'IMPÉRATIF</div> <div class="card-title-es serif">ذَهَبَ EN IMPERATIVO</div> <div class="card-sep"></div> <table class="conj-table"> <thead><tr><th>ضَمِير</th><th>اَلْأَمْر</th></tr></thead> <tbody> <tr><td class="ct-pron ar">أَنْتَ</td><td class="ct-ar ar fil">اِذْهَبْ</td></tr> <tr><td class="ct-pron ar">أَنْتِ</td><td class="ct-ar ar fil">اِذْهَبِي</td></tr> <tr><td class="ct-pron ar">أَنْتُمَا</td><td class="ct-ar ar fil">اِذْهَبَا</td></tr> <tr><td class="ct-pron ar">أَنْتُمْ</td><td class="ct-ar ar fil">اِذْهَبُوا</td></tr> <tr><td class="ct-pron ar">أَنْتُنَّ</td><td class="ct-ar ar fil">اِذْهَبْنَ</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Le tableau complet · La tabla completa</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Six verbes, un seul mécanisme</div></div> <div class="card-sep"></div> <table class="conj-table purple-header" style="font-size:0.72rem;"> <thead><tr><th>مَاضٍ</th><th>مُضَارِع</th><th>أَمْر</th></tr></thead> <tbody> <tr><td class="ct-ar ar ism">كَتَبَ</td><td class="ct-ar ar fil">يَكْتُبُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اُكْتُبْ</td></tr> <tr><td class="ct-ar ar ism">دَخَلَ</td><td class="ct-ar ar fil">يَدْخُلُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اُدْخُلْ</td></tr> <tr><td class="ct-ar ar ism">جَلَسَ</td><td class="ct-ar ar fil">يَجْلِسُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اِجْلِسْ</td></tr> <tr><td class="ct-ar ar ism">ضَرَبَ</td><td class="ct-ar ar fil">يَضْرِبُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اِضْرِبْ</td></tr> <tr><td class="ct-ar ar ism">فَتَحَ</td><td class="ct-ar ar fil">يَفْتَحُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اِفْتَحْ</td></tr> <tr><td class="ct-ar ar ism">ذَهَبَ</td><td class="ct-ar ar fil">يَذْهَبُ</td><td class="ct-ar ar" style="color:#7b5ea7;">اِذْهَبْ</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Dans la phrase · En la frase</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">اَلْأَمْرُ فِي الجُمْلَة</div> <div class="card-title-fr serif">L'IMPÉRATIF DANS LA PHRASE</div> <div class="card-title-es serif">EL IMPERATIVO EN LA FRASE</div> <div class="card-sep"></div> <div class="example-block"> <div class="ex-ar ar"><span class="hv">اِفْتَحِ</span> الكِتَابَ.</div> <div class="ex-fr">Ouvre le livre.</div> </div> <div class="example-block"> <div class="ex-ar ar"><span class="hv">اُكْتُبِ</span> الدَّرْسَ.</div> <div class="ex-fr">Écris la leçon.</div> </div> <div class="card-rule-fr" style="font-size:0.8rem;">💡 Devant اَلْ, le sukun final devient une petite kasra de liaison : اِفْتَحْ → اِفْتَحِ.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Encore des phrases · Más frases</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Encore des phrases</div></div> <div class="card-sep"></div> <div class="example-block"> <div class="ex-ar ar"><span class="hv">اِجْلِسْ</span> هُنَا.</div> <div class="ex-fr">Assieds-toi ici.</div> </div> <div class="example-block"> <div class="ex-ar ar"><span class="hv">اِذْهَبْ</span> إِلَى المَدْرَسَةِ.</div> <div class="ex-fr">Va à l'école.</div> </div> <div class="example-block"> <div class="ex-ar ar"><span class="hv">اُدْخُلِ</span> البَيْتَ.</div> <div class="ex-fr">Entre dans la maison.</div> </div> <div class="card-rule-fr" style="font-size:0.8rem;">Je repère : le verbe → c'est un ordre → à qui ? → l'action demandée → le sens.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Ne pas confondre · No confundir</div>`
    }
  ],

  /* ══════════════════════════════════ 5. بِنَاءُ المَعْنَى — construire le sens ══════════════════════════════════ */ laysa: [
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">لَا تَخْلِطْ!</div> <div class="card-title-fr serif">NE PAS CONFONDRE</div> <div class="card-title-es serif">NO CONFUNDIR</div> <div class="card-sep"></div> <table class="conj-table green-header"> <thead><tr><th>الشَّكْل</th><th>المَعْنَى</th></tr></thead> <tbody> <tr><td class="ct-ar ar ism">كَتَبَ</td><td class="ct-fr">il a écrit — مَاضٍ</td></tr> <tr><td class="ct-ar ar fil">يَكْتُبُ</td><td class="ct-fr">il écrit — مُضَارِع</td></tr> <tr><td class="ct-ar ar" style="color:#7b5ea7;">اُكْتُبْ</td><td class="ct-fr">écris ! — أَمْر</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Encore un exemple · Otro ejemplo</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">جَلَسَ / يَجْلِسُ / اِجْلِسْ</div></div> <div class="card-sep"></div> <table class="conj-table green-header"> <thead><tr><th>الشَّكْل</th><th>المَعْنَى</th></tr></thead> <tbody> <tr><td class="ct-ar ar ism">جَلَسَ</td><td class="ct-fr">il s'est assis — مَاضٍ</td></tr> <tr><td class="ct-ar ar fil">يَجْلِسُ</td><td class="ct-fr">il s'assoit — مُضَارِع</td></tr> <tr><td class="ct-ar ar" style="color:#7b5ea7;">اِجْلِسْ</td><td class="ct-fr">assieds-toi ! — أَمْر</td></tr> </tbody> </table> <div class="card-rule-fr" style="margin-top:8px;font-size:0.85rem;text-align:center;font-weight:700;color:var(--burgundy);">PASSÉ · PRÉSENT · ORDRE — je les reconnais immédiatement.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;بِنَاءُ المَعْنَى</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">بِنَاءُ المَعْنَى</div> <div class="card-title-fr serif">CONSTRUIRE LE SENS</div> <div class="card-title-es serif">CONSTRUIR EL SIGNIFICADO</div> <div class="card-sep"></div> <div class="card-rule-fr">Maintenant, je décode une phrase couche par couche :</div> <div class="example-block"> <div class="ex-ar ar"><span class="hn">لَا</span> <span class="hv">تَفْتَحِ</span> البَابَ.</div> <div class="ex-fr">N'ouvre pas la porte.</div> </div> <div class="card-rule-fr" style="font-size:0.82rem;">لَا + مُضَارِع مَجْزُوم = <strong>نَهْي</strong> (interdiction) — different de la simple négation !</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Nahy ou nafy ? · ¿Nahy o nafy?</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">نَهْي أَمْ نَفْي ؟</div></div> <div class="card-sep"></div> <table class="conj-table" style="font-size:0.8rem;"> <thead><tr><th>الجُمْلَة</th><th>المَعْنَى</th></tr></thead> <tbody> <tr><td class="ct-ar ar hn">لَا يَفْتَحُ</td><td class="ct-fr">il n'ouvre pas (نَفْي بَسِيط)</td></tr> <tr><td class="ct-ar ar hn">لَا تَفْتَحْ</td><td class="ct-fr">n'ouvre pas ! (نَهْي)</td></tr> </tbody> </table> <div class="card-rule-fr" style="margin-top:8px;font-size:0.82rem;">💡 Acquis réactivé du Module 13 — pas un nouveau cours sur الجزم.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Réactiver les possessifs · Reactivar los posesivos</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">تَذَكَّرْ الضَّمَائِر</div> <div class="card-title-fr serif">RÉACTIVER LES POSSESSIFS</div> <div class="card-title-es serif">REACTIVAR LOS POSESIVOS</div> <div class="card-sep"></div> <div class="example-block"> <div class="ex-ar ar"><span class="hv">اِفْتَحْ</span> كِتَابَكَ.</div> <div class="ex-fr">Ouvre ton livre.</div> </div> <div class="gabarit-box"> <div class="gabarit-ar ar" style="font-size:1.5rem;">كِتَابَكَ = كِتَاب + كَ</div> <div class="gabarit-label serif">ton livre — Module 15</div> </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Encore un exemple · Otro ejemplo</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">اُكْتُبُوا دَرْسَكُمْ</div></div> <div class="card-sep"></div> <div class="example-block"> <div class="ex-ar ar"><span class="hv">اُكْتُبُوا</span> دَرْسَكُمْ.</div> <div class="ex-fr">Écrivez votre leçon.</div> </div> <div class="gabarit-box"> <div class="gabarit-ar ar" style="font-size:1.5rem;">دَرْسَكُمْ = دَرْس + كُمْ</div> <div class="gabarit-label serif">votre leçon — Module 15</div> </div> <div class="card-rule-fr" style="margin-top:8px;font-size:0.85rem;">💡 Le mécanisme du Module 15 fonctionne exactement pareil ici — je ne refais pas le cours, je le réutilise.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Réactiver les accords · Reactivar las concordancias</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">تَذَكَّرْ النَّعْتَ</div> <div class="card-title-fr serif">RÉACTIVER LES ACCORDS</div> <div class="card-title-es serif">REACTIVAR LAS CONCORDANCIAS</div> <div class="card-sep"></div> <div class="example-block"> <div class="ex-ar ar"><span class="hv">اِقْرَأِ</span> الكِتَابَ <span class="hn">الجَدِيدَ</span>.</div> <div class="ex-fr">Lis le nouveau livre.</div> </div> <div class="card-rule-fr" style="font-size:0.85rem;">الكِتَابَ (مُذَكَّر) + الجَدِيدَ (مُذَكَّر) : le نَعْت s'accorde avec le مَنْعُوت — Module 14.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Réactiver la structure de la phrase · Reactivar la estructura</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">La phrase se transforme</div></div> <div class="card-sep"></div> <table class="conj-table" style="font-size:0.78rem;"> <thead><tr><th>الزَّمَن</th><th>الجُمْلَة</th></tr></thead> <tbody> <tr><td class="ct-fr">مَاضٍ</td><td class="ct-ar ar ism">كَتَبَ أَحْمَدُ الدَّرْسَ.</td></tr> <tr><td class="ct-fr">مُضَارِع</td><td class="ct-ar ar fil">يَكْتُبُ أَحْمَدُ الدَّرْسَ.</td></tr> <tr><td class="ct-fr">أَمْر</td><td class="ct-ar ar" style="color:#7b5ea7;">اُكْتُبِ الدَّرْسَ.</td></tr> </tbody> </table> <div class="card-rule-fr" style="margin-top:8px;font-size:0.82rem;">💡 Le sujet أَحْمَدُ disparaît à l'impératif — on s'adresse directement à quelqu'un. Le complément الدَّرْسَ reste identifiable (Modules 9-10).</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;La méthode finale de décodage</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.2rem,4vw,1.6rem);">أَقْرَأُ ← أُرَاقِبُ ← أُفَكِّكُ ← أَزِنُ ← أَرْبِطُ ← أَفْهَمُ</div> <div class="card-title-fr serif">LA MÉTHODE FINALE DE DÉCODAGE</div> <div class="card-title-es serif">EL MÉTODO FINAL DE DECODIFICACIÓN</div> <div class="card-sep"></div> <div style="font-family:'Amiri',serif;direction:rtl;font-size:0.85rem;color:var(--burgundy);line-height:2;text-align:center;"> ١ أَقْرَأُ — JE LIS<br> ٢ أُرَاقِبُ — J'OBSERVE<br> ٣ أُفَكِّكُ — JE DÉCOMPOSE<br> ٤ أَزِنُ — JE PÈSE le verbe<br> ٥ أَرْبِطُ — JE RELIE<br> ٦ أَفْهَمُ — JE COMPRENDS </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;La synthèse de la Partie 2 · La síntesis de la Parte 2</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">La synthèse de la Partie 2</div></div> <div class="card-sep"></div> <div class="card-rule-fr" style="text-align:center;">Cette méthode en 6 étapes résume tout ce que tu as appris depuis le Module 13 : observer, décomposer, peser un verbe, relier les indices (pronoms, accords, négation) et enfin comprendre.</div> <div class="card-rule-es" style="text-align:center;margin-top:6px;">Este método en 6 pasos resume todo lo aprendido desde el Módulo 13.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Fin de la Partie 2 · Fin de la Parte 2</div>`
    },
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">DAR AL-KALIMAH</div></div> <div class="card-sep"></div> <div class="card-title-ar ar" style="font-size:clamp(1.4rem,4.5vw,1.9rem);">نِهَايَةُ الجُزْءِ الثَّانِي</div> <div class="card-title-fr serif">FIN DE LA PARTIE 2</div> <div class="card-title-es serif">FIN DE LA PARTE 2</div> <div class="card-sep"></div> <table class="conj-table" style="font-size:0.7rem;"> <thead><tr><th>مُودُلَة</th><th>الموضوع</th></tr></thead> <tbody> <tr><td class="ct-fr">١٣</td><td class="ct-ar ar ism">اَلنَّفْي</td></tr> <tr><td class="ct-fr">١٤</td><td class="ct-ar ar ism">اَلنَّعْتُ وَالمَنْعُوت</td></tr> <tr><td class="ct-fr">١٥</td><td class="ct-ar ar ism">اَلضَّمَائِر</td></tr> <tr><td class="ct-fr">١٦</td><td class="ct-ar ar ism">اَلْفِعْلُ الْمَاضِي</td></tr> <tr><td class="ct-fr">١٧</td><td class="ct-ar ar ism">اَلْفِعْلُ الْمُضَارِع</td></tr> <tr><td class="ct-fr">١٨</td><td class="ct-ar ar fil">فِعْلُ الأَمْرِ</td></tr> </tbody> </table> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Le message final · El mensaje final</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Le message final</div></div> <div class="card-sep"></div> <div style="background:rgba(200,164,98,0.08);border:1px solid rgba(200,164,98,0.3);border-radius:14px;padding:16px;text-align:center;"> <div style="font-family:'Amiri',serif;direction:rtl;font-size:1.05rem;color:var(--burgundy);font-weight:700;line-height:1.9;">لَمْ تَعُدْ تَنْظُرُ إِلَى الجُمْلَةِ العَرَبِيَّةِ كَمَا كُنْتَ مِنْ قَبْلُ</div> <div style="font-size:0.82rem;color:var(--text-soft);margin-top:6px;">Tu ne regardes plus une phrase arabe comme avant. Tu sais maintenant observer sa structure, reconnaître des indices, décomposer les mots, identifier des formes verbales et construire progressivement le sens.<br><em>Ya no miras una frase árabe como antes. Sabes observar su estructura, reconocer indicios, descomponer palabras y construir el sentido.</em></div> </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;تَعْزِيزُ القِرَاءَة</div>`
    }
  ],

  /* ══════════════════════════════════ 6. تعزيز القراءة ══════════════════════════════════ */ qiraa: [
    {
      front:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">تَعْزِيزُ الْقِرَاءَة · TEXTE</div></div> <div class="card-sep"></div> <div class="qiraa-legend"> <div class="legend-item"><div class="legend-dot-v"></div><span>فِعْلُ الأَمْرِ — vert</span></div> <div class="legend-item"><div class="legend-dot-n"></div><span>أَكْتَسَبْتُهُ فِي مُودُلَة سَابِقَة — بوردو</span></div> </div> <div class="qiraa-title-fr serif">فِي الصَّفِّ · En classe · En clase</div> <div class="qiraa-text ar">يَقُولُ المُعَلِّمُ لِلطُّلَّابِ: <span class="hl-v">اِفْتَحُوا</span> كُتُبَكُمْ.</div> <div class="qiraa-text ar">يَفْتَحُ أَحْمَدُ كِتَابَهُ الجَدِيدَ وَيَقْرَأُ الدَّرْسَ.</div> <div class="qiraa-text ar">كَتَبَ أَحْمَدُ دَرْسَهُ أَمْسِ، وَالْيَوْمَ يَكْتُبُ وَاجِبَهُ.</div> <div class="qiraa-text ar">تَقُولُ مَرْيَمُ لِأُخْتِهَا الصَّغِيرَةِ: <span class="hl-v">اِجْلِسِي</span> هُنَا.</div> <div class="qiraa-text ar">ثُمَّ تَفْتَحُ أُخْتُهَا دَفْتَرَهَا وَتَكْتُبُ اسْمَهَا.</div> <div class="qiraa-text ar"><span class="hl-n">لَا</span> تَذْهَبُوا الْآنَ! يَقُولُ المُعَلِّمُ، <span class="hl-v">اُكْتُبُوا</span> الدَّرْسَ أَوَّلًا.</div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Traduction · Traducción</div>`,
      back:` <div class="card-brand"><div class="card-brand-ar ar">دار الكلمة</div><div class="card-brand-fr serif">Traduction · Traducción</div></div> <div style="font-size:0.82rem;line-height:1.5;padding:0 2px;"> <div style="padding:5px 0;border-bottom:1px solid rgba(200,164,98,0.15);"> <div style="color:var(--text-dark);">Le professeur dit aux élèves : Ouvrez vos livres.</div> <div style="color:var(--text-soft);font-style:italic;">El profesor dice a los alumnos: Abrid vuestros libros.</div> </div> <div style="padding:5px 0;border-bottom:1px solid rgba(200,164,98,0.15);"> <div style="color:var(--text-dark);">Ahmad ouvre son nouveau livre et lit la leçon.</div> <div style="color:var(--text-soft);font-style:italic;">Ahmad abre su libro nuevo y lee la lección.</div> </div> <div style="padding:5px 0;border-bottom:1px solid rgba(200,164,98,0.15);"> <div style="color:var(--text-dark);">Ahmad a écrit sa leçon hier, et aujourd'hui il écrit son devoir.</div> <div style="color:var(--text-soft);font-style:italic;">Ahmad escribió su lección ayer, y hoy escribe su tarea.</div> </div> <div style="padding:5px 0;border-bottom:1px solid rgba(200,164,98,0.15);"> <div style="color:var(--text-dark);">Maryam dit à sa petite sœur : Assieds-toi ici.</div> <div style="color:var(--text-soft);font-style:italic;">Maryam le dice a su hermana pequeña: Siéntate aquí.</div> </div> <div style="padding:5px 0;border-bottom:1px solid rgba(200,164,98,0.15);"> <div style="color:var(--text-dark);">Puis sa sœur ouvre son cahier et écrit son nom.</div> <div style="color:var(--text-soft);font-style:italic;">Luego su hermana abre su cuaderno y escribe su nombre.</div> </div> <div style="padding:5px 0;"> <div style="color:var(--text-dark);">N'allez pas maintenant ! dit le professeur, écrivez la leçon d'abord.</div> <div style="color:var(--text-soft);font-style:italic;">¡No vayáis ahora! dice el profesor, escribid la lección primero.</div> </div> </div> <div class="flip-hint serif"><i class="fa-solid fa-rotate"></i> &nbsp;Questions · Preguntas</div>`
    },
    { type:'quiz', num:1,
      ar:'هَلْ يَقُولُ المُعَلِّمُ لِلطُّلَّابِ: اِفْتَحُوا كُتُبَكُمْ؟',
      fr:'Le professeur dit-il aux élèves : Ouvrez vos livres ?', es:'¿El profesor dice a los alumnos: Abrid vuestros libros?',
      answer:true,
      ok_ar:'✓ صَحِيح — هَذَا مَا يَقُولُهُ المُعَلِّمُ', ok_fr:'Correct — c’est la première phrase du texte.', ok_es:'Correcto — es la primera frase del texto.',
      ko_ar:'✗ النَّصُّ يَقُولُ: اِفْتَحُوا كُتُبَكُمْ', ko_fr:'Non — relis la première phrase.', ko_es:'No — vuelve a leer la primera frase.'
    },
    { type:'quiz', num:2,
      ar:'هَلْ كَتَبَ أَحْمَدُ وَاجِبَهُ أَمْسِ؟',
      fr:'Ahmad a-t-il écrit son devoir hier ?', es:'¿Ahmad escribió su tarea ayer?',
      answer:false,
      ok_ar:'✓ صَحِيح — كَتَبَ دَرْسَهُ أَمْسِ، وَيَكْتُبُ وَاجِبَهُ الْيَوْمَ', ok_fr:'Correct — il a écrit sa leçon hier ; c’est son devoir qu’il écrit aujourd’hui.', ok_es:'Correcto — escribió su lección ayer; hoy escribe su tarea.',
      ko_ar:'✗ أَمْسِ كَتَبَ دَرْسَهُ، لَا وَاجِبَهُ', ko_fr:'Non — hier il a écrit sa LEÇON, pas son devoir.', ko_es:'No — ayer escribió su LECCIÓN, no su tarea.'
    },
    { type:'quiz', num:3,
      ar:'هَلْ تَقُولُ مَرْيَمُ لِأُخْتِهَا: اِذْهَبِي؟',
      fr:'Maryam dit-elle à sa sœur : Va-t’en ?', es:'¿Maryam le dice a su hermana: Vete?',
      answer:false,
      ok_ar:'✓ صَحِيح — تَقُولُ: اِجْلِسِي هُنَا، لَا اِذْهَبِي', ok_fr:'Correct — elle dit « اِجْلِسِي » (assieds-toi), pas « اِذْهَبِي ».', ko_ar:'',
      ok_es:'Correcto — dice «اِجْلِسِي» (siéntate), no «اِذْهَبِي».',
      ko_fr:'Non — le texte dit اِجْلِسِي هُنَا.', ko_es:'No — el texto dice اِجْلِسِي هُنَا.'
    },
    { type:'mcq',
      ar:'مَا هُوَ فِعْلُ الأَمْرِ فِي الجُمْلَةِ الأُولَى؟', fr:'Quel est le verbe à l’impératif dans la première phrase ?', es:'¿Cuál es el verbo en imperativo en la primera frase?',
      opts:['اِفْتَحُوا','يَقُولُ','كُتُبَكُمْ'], correct:0,
      fb_ok_ar:'✓ اِفْتَحُوا هُوَ فِعْلُ الأَمْرِ', fb_ok_fr:'Correct — « اِفْتَحُوا » (ouvrez) est l’impératif.', fb_ok_es:'Correcto — «اِفْتَحُوا» (abrid) es el imperativo.',
      fb_ko_ar:'✗ الفِعْلُ اِفْتَحُوا هُوَ الأَمْر', fb_ko_fr:'Non — c’est un ordre adressé aux élèves : اِفْتَحُوا.', fb_ko_es:'No — es una orden a los alumnos: اِفْتَحُوا.'
    },
    { type:'mcq',
      ar:'فِي (اِجْلِسِي)، إِلَى مَنْ يَتَوَجَّهُ الكَلَامُ؟', fr:'Dans « اِجْلِسِي », à qui s’adresse-t-on ?', es:'En «اِجْلِسِي», ¿a quién se dirige?',
      opts:['أَنْتِ','أَنْتَ','أَنْتُمْ'], correct:0,
      fb_ok_ar:'✓ اِجْلِسِي مُوَجَّهَةٌ إِلَى أَنْتِ (المُؤَنَّثَة)', fb_ok_fr:'Correct — la terminaison ي marque أَنْتِ.', fb_ok_es:'Correcto — la terminación ي marca أَنْتِ.',
      fb_ko_ar:'✗ اَلْعَلَامَةُ ي تُشِيرُ إِلَى أَنْتِ', fb_ko_fr:'Non — la marque ي correspond à أَنْتِ (féminin).', fb_ko_es:'No — la marca ي corresponde a أَنْتِ (femenino).'
    },
    { type:'mcq',
      ar:'كَلِمَةُ (وَاجِبَهُ) مُكَوَّنَةٌ مِنْ:', fr:'Le mot « وَاجِبَهُ » est composé de :', es:'La palabra «وَاجِبَهُ» está compuesta de:',
      opts:['وَاجِب + هُ','وَاجِب + هَا','وَاجِب + كُمْ'], correct:0,
      fb_ok_ar:'✓ وَاجِب + هُ = son devoir (à lui)', fb_ok_fr:'Correct — هُ est le possessif de هُوَ (Module 15).', fb_ok_es:'Correcto — هُ es el posesivo de هُوَ.',
      fb_ko_ar:'✗ اللَّاحِقَةُ هُ تَعُودُ إِلَى أَحْمَدَ (هُوَ)', fb_ko_fr:'Non — هُ renvoie à Ahmad (هُوَ).', fb_ko_es:'No — هُ se refiere a Ahmad (هُوَ).'
    },
    { type:'mcq',
      ar:'الفِعْلُ (اِفْتَحُوا) يُقَابِلُ فِي المُضَارِعِ:', fr:'Le verbe « اِفْتَحُوا » correspond au présent :', es:'El verbo «اِفْتَحُوا» corresponde al presente:',
      opts:['يَفْتَحُ','تَفْتَحُونَ','نَفْتَحُ'], correct:1,
      fb_ok_ar:'✓ اِفْتَحُوا ← تَفْتَحُونَ (أَنْتُمْ)', fb_ok_fr:'Correct — l’impératif pluriel vient du présent تَفْتَحُونَ.', fb_ok_es:'Correcto — el imperativo plural viene del presente تَفْتَحُونَ.',
      fb_ko_ar:'✗ اِفْتَحُوا مِنْ تَفْتَحُونَ (أَنْتُمْ)', fb_ko_fr:'Non — اِفْتَحُوا s’adresse à أَنْتُمْ, donc تَفْتَحُونَ.', fb_ko_es:'No — اِفْتَحُوا se dirige a أَنْتُمْ, por eso تَفْتَحُونَ.'
    },
    { type:'mcq',
      ar:'لِمَاذَا يَقُولُ المُعَلِّمُ لِلطُّلَّابِ أَلَّا يَذْهَبُوا الآنَ؟', fr:'Pourquoi le professeur dit-il aux élèves de ne pas partir maintenant ?', es:'¿Por qué el profesor dice a los alumnos que no se vayan ahora?',
      opts:['لِيَكْتُبُوا الدَّرْسَ أَوَّلًا','لِأَنَّهُمْ مَرْضَى','لِأَنَّ البَابَ مُغْلَقٌ'], correct:0,
      fb_ok_ar:'✓ لِيَكْتُبُوا الدَّرْسَ أَوَّلًا', fb_ok_fr:'Correct — il faut écrire la leçon d’abord.', fb_ok_es:'Correcto — hay que escribir la lección primero.',
      fb_ko_ar:'✗ السَّبَبُ: يَكْتُبُونَ الدَّرْسَ أَوَّلًا', fb_ko_fr:'Non — la raison est d’écrire la leçon d’abord.', fb_ko_es:'No — la razón es escribir la lección primero.'
    }
  ]
};

/* ══ STATE & RENDU ══ */
const State = { fil:     {idx:0,flipped:false}, madhi:   {idx:0,flipped:false}, mudhari: {idx:0,flipped:false}, amr:     {idx:0,flipped:false}, laysa:   {idx:0,flipped:false}, qiraa:   {idx:0,flipped:false}
};

const $=id=>document.getElementById(id);
const views={select:$("view-select"),fil:$("view-fil"),madhi:$("view-madhi"),mudhari:$("view-mudhari"),amr:$("view-amr"),laysa:$("view-laysa"),qiraa:$("view-qiraa")};

function showView(n){Object.values(views).forEach(v=>v.classList.add("hidden"));views[n].classList.remove("hidden");}

function renderSection(section){
const s=State[section];
const cards=DATA[section];
const card=cards[s.idx]; s.flipped=false;
const flip=$("card-"+section); flip.classList.remove("flipped");

if(card.type==='quiz'){ flip.onclick=null;flip.style.cursor='default';
var adat=card.adat?'<span class="ar" style="font-family:Amiri,serif;font-size:1.8rem;color:var(--gold);direction:rtl;font-weight:700;font-feature-settings:\'liga\' 1,\'calt\' 1,\'mark\' 1,\'mkmk\' 1;">'+card.adat+'</span> ':''; $(section+"-front").innerHTML= '<div class="card-brand" style="margin-bottom:8px;"><div class="card-brand-ar ar" style="font-size:2rem;">دار الكلمة</div>' +'<div class="card-brand-fr serif" style="font-size:0.8rem;letter-spacing:2px;color:var(--burgundy);opacity:0.8;">تَعْزِيزُ الْقِرَاءَة</div></div>' +'<div class="card-sep"></div>' +'<div class="quiz-num">QUESTION '+card.num+' / 3 &nbsp;·&nbsp; PREGUNTA '+card.num+' / 3</div>' +'<div style="text-align:center;margin:6px 0 10px;">'+adat+'</div>' +'<div class="quiz-q-ar ar">'+card.ar+'</div>' +'<div class="quiz-q-fr">'+card.fr+'</div>' +'<div class="quiz-q-es">'+card.es+'</div>' +'<div class="quiz-btns">' +'<button class="quiz-btn quiz-btn-oui" onclick="answerQuiz(\''+section+'\',true)">نعم<br><small>Oui · Sí</small></button>' +'<button class="quiz-btn quiz-btn-non" onclick="answerQuiz(\''+section+'\',false)">لا<br><small>Non · No</small></button>' +'</div><div class="quiz-feedback" id="qfb-'+section+'"></div>'; $(section+"-back").innerHTML='';
  } else if(card.type==='mcq'){ flip.onclick=null;flip.style.cursor='default';
var adat2=card.adat?'<span class="ar" style="font-family:Amiri,serif;font-size:1.8rem;color:var(--gold);direction:rtl;font-weight:700;font-feature-settings:\'liga\' 1,\'calt\' 1,\'mark\' 1,\'mkmk\' 1;">'+card.adat+'</span> ':'';
var optsHtml=''; card.opts.forEach(function(opt,i){ optsHtml+='<button class="mcq-btn" onclick="answerMCQ(\''+section+'\','+i+')" data-idx="'+i+'">' +'<span class="ar" style="font-family:Amiri,serif;font-size:clamp(1rem,3.5vw,1.3rem);direction:rtl;font-feature-settings:\'liga\' 1,\'calt\' 1,\'mark\' 1,\'mkmk\' 1;">'+opt+'</span></button>';
    }); $(section+"-front").innerHTML= '<div class="card-brand" style="margin-bottom:8px;"><div class="card-brand-ar ar" style="font-size:2rem;">دار الكلمة</div>' +'<div class="card-brand-fr serif" style="font-size:0.8rem;letter-spacing:2px;color:var(--burgundy);opacity:0.8;">تَعْزِيزُ الْقِرَاءَة</div></div>' +'<div class="card-sep"></div>' +'<div style="text-align:center;margin:6px 0 10px;">'+adat2+'</div>' +'<div class="quiz-q-ar ar">'+card.ar+'</div>' +'<div class="quiz-q-fr">'+card.fr+'</div>' +'<div class="quiz-q-es" style="margin-bottom:12px;">'+card.es+'</div>' +'<div style="width:100%;margin-bottom:10px;">'+optsHtml+'</div>' +'<div class="quiz-feedback" id="qfb-'+section+'"></div>'; $(section+"-back").innerHTML='';
  } else { flip.onclick=function(){flipCard(section);}; flip.style.cursor='pointer'; $(section+"-front").innerHTML=card.front; $(section+"-back").innerHTML=card.back;
  }
 $(section+"-curr").textContent=s.idx+1;
if($(section+"-tot"))$(section+"-tot").textContent=cards.length; $(section+"-prev").disabled=(s.idx===0); $(section+"-next").disabled=(s.idx===cards.length-1); $(section+"-front").scrollTop=0; $(section+"-back").scrollTop=0;
if(section==='qiraa'&&s.idx===cards.length-1){
enrLecon18(cards.length);
}
}

window.answerQuiz=function(section,chosen){
var card=DATA[section][State[section].idx];
var fb=document.getElementById('qfb-'+section);
var correct=(chosen===card.answer); document.querySelectorAll('#view-'+section+' .quiz-btn').forEach(function(b){b.disabled=true;}); fb.className='quiz-feedback show '+(correct?'correct':'wrong');
var ar=correct?card.ok_ar:card.ko_ar;
var fr=correct?card.ok_fr:card.ko_fr;
var es=correct?card.ok_es:card.ko_es; fb.innerHTML='<div style="font-family:Amiri,serif;font-size:1rem;direction:rtl;margin-bottom:5px;font-feature-settings:\'liga\' 1,\'calt\' 1,\'mark\' 1,\'mkmk\' 1;">'+ar+'</div><div style="margin-bottom:3px;font-weight:600;">'+fr+'</div><em>'+es+'</em>';
};

window.answerMCQ=function(section,chosen){
var card=DATA[section][State[section].idx];
var fb=document.getElementById('qfb-'+section);
var correct=(chosen===card.correct); document.querySelectorAll('#view-'+section+' .mcq-btn').forEach(function(b){b.disabled=true;});
var chosenBtn=document.querySelector('#view-'+section+' .mcq-btn[data-idx="'+chosen+'"]');
var correctBtn=document.querySelector('#view-'+section+' .mcq-btn[data-idx="'+card.correct+'"]');
if(correct){chosenBtn.classList.add('mcq-correct');} else{chosenBtn.classList.add('mcq-wrong');if(correctBtn)correctBtn.classList.add('mcq-correct');} fb.className='quiz-feedback show '+(correct?'correct':'wrong');
var ar=correct?card.fb_ok_ar:card.fb_ko_ar;
var fr=correct?card.fb_ok_fr:card.fb_ko_fr;
var es=correct?card.fb_ok_es:card.fb_ko_es; fb.innerHTML='<div style="font-family:Amiri,serif;font-size:1rem;direction:rtl;margin-bottom:5px;font-feature-settings:\'liga\' 1,\'calt\' 1,\'mark\' 1,\'mkmk\' 1;">'+ar+'</div><div style="margin-bottom:3px;font-weight:600;">'+fr+'</div><em>'+es+'</em>';
};

window.openSection=function(section){
State[section].idx=0;State[section].flipped=false; renderSection(section);showView(section);
};
window.goHome=function(){showView("select");};
window.flipCard=function(section){
State[section].flipped=!State[section].flipped; $("card-"+section).classList.toggle("flipped",State[section].flipped);
};

    var _enrLecon18Enregistree = false;
    function enrLecon18(cartesTotal) {
        if (_enrLecon18Enregistree) return;
        if (window.DAK_enregistrerLecon) {
            _enrLecon18Enregistree = true;
            window.DAK_enregistrerLecon({ module: 'Module 18', lecon: 'Leçon 18', total: cartesTotal });
            return;
        }
        var _t = 0;
        var _iv = setInterval(function() {
            _t++;
            if (window.DAK_enregistrerLecon && !_enrLecon18Enregistree) {
                _enrLecon18Enregistree = true;
                clearInterval(_iv);
                window.DAK_enregistrerLecon({ module: 'Module 18', lecon: 'Leçon 18', total: cartesTotal });
            } else if (_t >= 15) { clearInterval(_iv); }
        }, 200);
    }
    window.navigate=function(section,dir){
var s=State[section];
var next=s.idx+dir;
if(next<0||next>=DATA[section].length)return; s.idx=next;renderSection(section);
};

["fil","madhi","mudhari","amr","laysa","qiraa"].forEach(function(section){
var tx=0;
var el=$("view-"+section); el.addEventListener("touchstart",function(e){tx=e.touches[0].clientX;},{passive:true}); el.addEventListener("touchend",function(e){
var dx=tx-e.changedTouches[0].clientX;
if(Math.abs(dx)>55){dx>0?navigate(section,1):navigate(section,-1);}
  },{passive:true});
});

})();
